import {
  NextPage,
  GetServerSideProps,
  InferGetServerSidePropsType
} from 'next';
import Head from 'next/head';
import Header from '../../components/Header';

import Return from '../../assets/return.svg';
import ArrowRegion from '../../assets/arrowRegion.svg';
import StarEmpty from '../../assets/starEmpty.svg';
import StarFull from '../../assets/starFull.svg';
import RoundEmpty from '../../assets/roundEmpty.svg';
import RoundEmptyFade from '../../assets/roundEmptyFade.svg';

import {
  ButtonContainer,
  Container,
  ContainerReturn,
  Content,
  ContentLeft,
  ContentRight,
  DescriptionContainer,
  InfoContainer,
  PricesContainer,
  ProductHeader,
  RegionContainer
} from '../../styles/pages/Product';

interface Item {
  id: number;
  image: string;
  name: string;
  price: number;
  discount: number;
  priceMember: number;
  priceNonMember: number;
  type: string;
  classification: string;
  size: string;
  rating: number;
  avaliations: number;
  country: string;
  region: string;
  flag: string;
  sommelierComment: string;
}

interface Data {
  page: number;
  totalPages: number;
  itemsPerPage: number;
  totalItems: number;
  items: Item[];
}

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  const res = await fetch(`https://wine-back-test.herokuapp.com/products?`);
  const data: Data = await res.json();
  const findProduct: Item = data.items.find(
    product => product.id === +params.product
  );

  return {
    props: {
      findProduct
    }
  };
};

const Product: NextPage = ({
  findProduct
}: InferGetServerSidePropsType<typeof getServerSideProps>) => (
  <div>
    <Head>
      <title>Wine</title>
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>

    <Header />
    <main>
      <Container>
        <ContainerReturn>
          <Return />
          Voltar
        </ContainerReturn>
        <Content>
          <ContentLeft>
            <img src={findProduct.image} alt={findProduct.name} />
          </ContentLeft>
          <ContentRight>
            <ProductHeader>
              <RegionContainer>
                <span>Vinhos</span>
                <ArrowRegion />
                <span>{findProduct.country}</span>
                <ArrowRegion />
                <span>{findProduct.region}</span>
              </RegionContainer>
              <h1>{findProduct.name}</h1>
              <InfoContainer>
                <img src={findProduct.flag} alt={findProduct.country} />
                <p>{findProduct.country}</p>
                <p>{findProduct.type}</p>
                <p>{findProduct.classification}</p>
                <p>{findProduct.size}</p>
                {findProduct.rating > 0 ? <StarFull /> : <StarEmpty />}
                {findProduct.rating > 1 ? <StarFull /> : <StarEmpty />}
                {findProduct.rating > 2 ? <StarFull /> : <StarEmpty />}
                {findProduct.rating > 3 ? <StarFull /> : <StarEmpty />}
                {findProduct.rating > 4 ? <StarFull /> : <StarEmpty />}
                <p>({findProduct.avaliations})</p>
              </InfoContainer>
            </ProductHeader>
            <PricesContainer>
              <p>R${findProduct.priceMember}</p>
              <span>NÃO SÓCIO R${findProduct.priceNonMember}/UN.</span>
            </PricesContainer>
            <DescriptionContainer>
              <h3>Comentário do Sommelier</h3>
              <p>{findProduct.sommelierComment}</p>
            </DescriptionContainer>
            <ButtonContainer>
              <div>
                <RoundEmptyFade />
                <p>-</p>1<p>+</p>
                <RoundEmpty />
              </div>
              <div>Adicionar</div>
            </ButtonContainer>
          </ContentRight>
        </Content>
      </Container>
    </main>
  </div>
);

export default Product;
