import {
  NextPage,
  GetServerSideProps,
  InferGetServerSidePropsType
} from 'next';
import Head from 'next/head';
import Header from '../../components/Header';

import Return from '../../assets/return.svg';
import ArrowRegion from '../../assets/arrowRegion.svg';

import {
  Container,
  ContainerReturn,
  Content,
  ContentLeft,
  ContentRight,
  RegionContainer
} from '../../styles/pages/Product';

interface Item {
  id: number;
  image: string;
  name: string;
  price: number;
  discount: number;
  priceMember: number;
  priceNonMember: number;
  type: string;
  classification: string;
  size: string;
  rating: number;
  avaliations: number;
  country: string;
  region: string;
  flag: string;
  sommelierComment: string;
}

interface Data {
  page: number;
  totalPages: number;
  itemsPerPage: number;
  totalItems: number;
  items: Item[];
}

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  const res = await fetch(`https://wine-back-test.herokuapp.com/products?`);
  const data: Data = await res.json();
  const findProduct: Item = data.items.find(
    product => product.id === +params.product
  );

  return {
    props: {
      findProduct
    }
  };
};

const Product: NextPage = ({
  findProduct
}: InferGetServerSidePropsType<typeof getServerSideProps>) => (
  <div>
    <Head>
      <title>Wine</title>
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>

    <Header />
    <main>
      <Container>
        <ContainerReturn>
          <Return />
          Voltar
        </ContainerReturn>
        <Content>
          <ContentLeft>
            <img src={findProduct.image} alt={findProduct.name} />
          </ContentLeft>
          <ContentRight>
            <RegionContainer>
              <span>Vinhos</span>
              <ArrowRegion />
              <span>{findProduct.country}</span>
              <ArrowRegion />
              <span>{findProduct.region}</span>
            </RegionContainer>
            <h1>{findProduct.name}</h1>
          </ContentRight>
        </Content>
      </Container>
    </main>
  </div>
);

export default Product;
