import { NextPage } from 'next';
import Head from 'next/head';

import Header from '../components/header/Header';
import Container from '../styles/pages/Cart';
import ProductsGridCart from '../components/cart/ProductsGridCart';
import FooterCart from '../components/cart/FooterCart';

const Cart: NextPage = () => (
  <div>
    <Head>
      <title>Wine | Compre vinhos online com descontos exclusivos!</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <Header />
    <main>
      <Container>
        <ProductsGridCart />
        <FooterCart />
      </Container>
    </main>
  </div>
);

export default Cart;
