import { NextPage } from 'next';
import Head from 'next/head';

import Search from '../assets/search.svg';
import ProductsList from '../components/ProductsList';
import { Container } from '../styles/pages/Home';

const Home: NextPage = () => (
  <Container>
    <Head>
      <title>Wine</title>
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>

    <main>
      <h1>Hello, world!</h1>
      <ProductsList />
      <Search />
    </main>
  </Container>
);

export default Home;
