import {
  NextPage,
  GetServerSideProps,
  InferGetServerSidePropsType
} from 'next';
import Head from 'next/head';
import Link from 'next/link';

import Search from '../assets/search.svg';
import { Container } from '../styles/pages/Home';

interface Item {
  id: number;
  image: string;
  name: string;
  price: number;
  discount: number;
  priceMember: number;
  priceNonMember: number;
  type: string;
  classification: string;
  size: string;
  rating: number;
  avaliations: number;
  country: string;
  region: string;
  flag: string;
  sommelierComment: string;
}

interface Data {
  page: number;
  totalPages: number;
  itemsPerPage: number;
  totalItems: number;
  items: Item[];
}

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch(
    'https://wine-back-test.herokuapp.com/products?page=1&limit=10'
  );
  const data: Data = await res.json();

  return {
    props: {
      data
    }
  };
};

const Home: NextPage = ({
  data
}: InferGetServerSidePropsType<typeof getServerSideProps>) => (
  <Container>
    <Head>
      <title>Wine</title>
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>

    <main>
      <h1>Home</h1>
      <ul>
        {data.items.map(product => (
          <li key={product.id}>
            {product.id} -
            <Link href={`/search/${product.name}`}>{product.name}</Link>
          </li>
        ))}
      </ul>
      <Search />
    </main>
  </Container>
);

export default Home;
