import {
  NextPage,
  GetServerSideProps,
  InferGetServerSidePropsType
} from 'next';
import Head from 'next/head';
import Link from 'next/link';

import Search from '../assets/search.svg';
import { Data } from '../interfaces/products';
import { Container } from '../styles/pages/Home';

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch(
    'https://wine-back-test.herokuapp.com/products?page=1&limit=10'
  );
  const data: Data = await res.json();

  return {
    props: {
      data
    }
  };
};

const Home: NextPage = ({
  data
}: InferGetServerSidePropsType<typeof getServerSideProps>) => (
  <Container>
    <Head>
      <title>Wine</title>
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>

    <main>
      <h1>Home</h1>
      <ul>
        {data.items.map(product => (
          <li key={product.id}>
            {product.id} -
            <Link href={`/search/${product.name}`}>{product.name}</Link>
          </li>
        ))}
      </ul>
      <Search />
    </main>
  </Container>
);

export default Home;
