import {
  NextPage,
  GetServerSideProps,
  InferGetServerSidePropsType
} from 'next';
import Head from 'next/head';
import { Data } from '../../interfaces/products';

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  const res = await fetch(
    `https://wine-back-test.herokuapp.com/products?name=${params.details}`
  );
  const data: Data = await res.json();

  return {
    props: {
      data
    }
  };
};

const Details: NextPage = ({
  data
}: InferGetServerSidePropsType<typeof getServerSideProps>) => (
  <div>
    <Head>
      <title>Details</title>
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>

    <main>
      <h1>Details</h1>
      <ul>
        {data.items.map(product => (
          <li key={product.id}>
            {product.id} - {product.name}
          </li>
        ))}
      </ul>
    </main>
  </div>
);

export default Details;
