import {
  NextPage,
  GetServerSideProps,
  InferGetServerSidePropsType
} from 'next';
import Head from 'next/head';
import Link from 'next/link';

import Header from '../../components/Header';
import { Data } from '../../interfaces/products';

export const getServerSideProps: GetServerSideProps = async ({
  params,
  query
}) => {
  const res = await fetch(
    `https://wine-back-test.herokuapp.com/products?page=${params.page}&limit=10&filter=${query.price}`
  );
  const data: Data = await res.json();

  return {
    props: {
      data
    }
  };
};

const Page: NextPage = ({
  data
}: InferGetServerSidePropsType<typeof getServerSideProps>) => (
  <div>
    <Head>
      <title>Wine</title>
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>

    <Header />
    <main>
      <h1>Page {data.page}</h1>
      <ul>
        {data.totalItems} itens encontrados
        {data.items.map(product => (
          <li key={product.id}>
            {product.id} -
            <Link href={`/product/${product.id}`}>{product.name}</Link>
          </li>
        ))}
      </ul>
    </main>
  </div>
);

export default Page;
